source 'https://rubygems.org'

gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'bootstrap-sass', '~> 3.3.0.1'
gem 'sass-rails', '>= 3.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'bootstrap-material-design', path: '../../../bootstrap-material-design'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
